services:
  - type: web
    plan: starter
    name: Jornal IF Baiano
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: SECRET_KEY
        gerenerateValue: true
      - key: DEBUG
        value: False