# Generated by Django 5.2.1 on 2025-08-12 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_perfil_foto_de_perfil'),
        ('news', '0005_noticia_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.perfil'),
        ),
    ]
