# Generated by Django 5.2.1 on 2025-08-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, default='static/img/default.jpg', upload_to='uploads/perfis'),
        ),
    ]
